language: go

go:
  - "1.13"

env:
  - CRDB_TAG=v19.2.2
  - CRDB_TAG=latest

services:
  - docker

git:
  depth: 1

notifications:
  email: false

before_install:
  - docker run -d --name=roach -p 26257:26257 cockroachdb/cockroach:${CRDB_TAG} start --insecure
  - sudo docker cp roach:/cockroach/cockroach /usr/local/bin/cockroach

script:
  - go test -p 1 -v -race ./...